### ISSUE TITLE
Russian language support

### ISSUE THREAD

**Issue by nmingazov** [innosoft-pro/label-them#20]
<img width="581" alt="screen shot 2017-06-27 at 18 07 42" src="https://user-images.githubusercontent.com/7488302/27594910-d31ba10e-5b63-11e7-9faf-9b4c4c75a604.png">

**Comment by AlNedorezov** [comment]
@nmingazov I believe the issue is not actually connected to the support of Russian language, but rather to a Toloka-related bug, which was fixed in [e33dc49d8330de7bc18e6581d4d96a52ac1f11cb](https://github.com/innosoft-pro/label-them/commit/e33dc49d8330de7bc18e6581d4d96a52ac1f11cb) commit, which is now merged into the master branch.
The details of the issue:
Toloka wraps the content of the systems body in two additional div's, one of which (one with "task" class) is seemingly have its own style, according to which the system re-scales itself from assuming all screens width, because of which users may have received "Image cannot fit the screen" warnings even if image perfectly fitted the screen.

**Comment by AlNedorezov** [comment]
@nmingazov users can scroll the image to unwrap its currently unseen parts regardless of the selected mode ("polygon" or "hand").

**Comment by nmingazov** [comment]
The issue with resizing itself is ok. Nevertheless, users who don't know English can't use instruction fully, and that since our average user is not supposed to be highly educated is the main problem. Therefore, we should consider adding some kind of translation tables.

**Comment by nmingazov** [comment]
Looks good.
