### ISSUE TITLE
Show blob classes near each marked blob

### ISSUE THREAD

**Issue by mihbort** [innosoft-pro/label-them#25]
In delayed acceptance mod it can be very useful to have such feature. Now I have to manually click on each blob to check its class.
This will be also good at marking stage. Mechanical Turks will see what is already marked and how and what is not marked yet. 
I think also would be good to have button which will be turn on and off such labels. 
For example, that way this feature looks in TensorFlow:
![screen shot 2017-07-12 at 16 07 58](https://user-images.githubusercontent.com/11292442/28119110-55ce63d4-671c-11e7-86cb-087ea095978a.png)

**Comment by nmingazov** [comment]
Is that related only to classes or to parameters as well?
I believe that classes only should be enough, just because they're guaranteed to be in the configuration file, while params could be empty.

**Comment by AlNedorezov** [comment]
@mihbort, thank you for the suggestion!

Starting from [release 1.6](https://github.com/innosoft-pro/label-them/releases/tag/v1.6), the system allows to view classes of marked up objects on the image itself, as during the markup process, as well as during the delayed acceptance.

An example marked up image with objects of different classes:
![Classes of the marked up object are displayed over the markup](https://s18.postimg.org/vmds0m73t/Screenshot_from_2017-07-26_22-23-38.png)

As you can see, objects of the same class are highlighted with the same color, to improve the speed of objects classes recognition.
Researches can define the colors for the classes manually (please, refer to the [Classes and parameters JSON description](https://github.com/innosoft-pro/label-them/wiki/Classes-and-parameters-JSON-description#configuring-class-colors) for details), otherwise different highlighting colors for each class will be assigned automatically.
