### ISSUE TITLE
Reset current marks by "esc" key

### ISSUE THREAD

**Issue by AleksandrShepelev** [innosoft-pro/label-them#28]
I know that there is Ctrl+Z buttons for this,  but I did not think about it first time

**Comment by AlNedorezov** [comment]
@AleksandrShepelev you can also cancel the ongoing markup of the object (removing all of the point of the ongoing, meaning the polygon is not closed yet, markup of the object) by right-click, which we have found more convenient, since it is faster then pressing the "esc" button, as you don't actually need the keyboard for it.

**Comment by AleksandrShepelev** [comment]
one more question, where I can find all the hotkeys that exist in project?

**Comment by AlNedorezov** [comment]
@AleksandrShepelev you can find hotkeys description in the hints on the [Adding annotations to an image](https://github.com/innosoft-pro/label-them/wiki/Adding-annotations-to-an-image) wiki page.
