### ISSUE TITLE
Don't want to click save and/or choose instrument

### ISSUE THREAD

**Issue by nmingazov** [innosoft-pro/label-them#8]
We have only one instrument. Moreover, saving should be triggered upon "Next" button click.

**Comment by AlNedorezov** [comment]
Starting from [v1.1](https://github.com/innosoft-pro/label-them/releases/tag/v1.1) polygon instrument is selected by default.
Starting from commit [8f90225ebec0403619170f452bda5bd6f9543a9c](https://github.com/innosoft-pro/label-them/commit/8f90225ebec0403619170f452bda5bd6f9543a9c) clicking "Save" button is not mandatory, all markup data is being saved before user presses "Next" button.

Since currently there is no user notifications about status of the markup (whether it was saved or not), the "Save" button is still visible & operational. Users can click on it if they worry about the markup status and their markup results will be recorder as an answer to the job in Yandex.Toloka (or, simplier, re-saved).

**Comment by nmingazov** [comment]
Ok, I'll test it.
1) Is it in develop-toloka branch or everything is in master branch now?
2) Isn't latest commit supposed to be inside release too?
3) Do we notify a user about this behavior?

**Comment by AlNedorezov** [comment]
Thank you.
1. It is in develop-toloka branch at the moment.
2. We'll​ make a new release as soon as we document polygons deletion and undoing latest markup points on the wiki, since those features are planned for the same release.
3. Currently, no. As I mentioned in the previous comment this is the reason why "save" button is still visible & operational, so that the users won't be worried whether their markup is saved.
I am thinking about implementing Google docs-like notifications about the saving of the latest markup changes in the future, but it needs more consideration.

**Comment by nmingazov** [comment]
Ok, thanks, I'll give it a try. :)
