### ISSUE TITLE
Characteristics moves away

### ISSUE THREAD

**Issue by nmingazov** [innosoft-pro/label-them#9]
Also, it's not possible to know which object is being marked.
https://drive.google.com/file/d/0BxiHDYc6uk9PbFF4OEc3RWEwX28/view?usp=sharing

**Comment by AlNedorezov** [comment]
@nmingazov, please, check on your machine whether this bug is still actual on the latest version of the system, which can be found in [develop-toloka branch](https://github.com/innosoft-pro/label-them/tree/develop-toloka).
If so, please share the information about the size of the images the bug was found with, the screen resolution of your machine, used OS, browser and its version.

**Comment by AlNedorezov** [comment]
I managed to reproduce the bug by zooming out the screen size to 33% or 25% (see [screencast](https://drive.google.com/file/d/0B_A9nop45WwKcE5TUU4wNzRNVFE/view?usp=sharing)), therefore having 5690+ px screen width (which I wouldn't call "normal operational condition", since not even iMac with Retina 5K (5120×2880) Display have such screen width). With the smaller screen resolution I wasn't able to reproduce this bug.

Test was performed in Chromium Browser version 58.0.3029.110 Built on Ubuntu, running on LinuxMint 18.1 (64-bit), with 640x480, 1698x1131, 343x227, and 220x462 images on a machine with Full HD screen resolution.

**Comment by AlNedorezov** [comment]
In order to improve usability, values of a class and parameters in the "Label Parameters" block are now reset at the beginning of the marking up of a new polygon (Check out latest version of the system in [develop-toloka branch](https://github.com/innosoft-pro/label-them/tree/develop-toloka)). Therefore, the values in the "Label Parameters" block relates to the polygon which was added last.
We will think about visual distinction of the polygon which parameters are shown in the "Label Parameters" during the implementation of the selection of the polygon.
